create table cloth
(
    id                     int8 not null,
    country                varchar(255),
    description            varchar(255),
    filename               varchar(255),
    base_notes             varchar(255),
    middle_notes           varchar(255),
    top_notes              varchar(255),
    gender                 varchar(255),
    title                  varchar(255),
    color                  varchar(255),
    price                  float8,
    type                   varchar(255),
    size                   varchar(255),
    brand                  varchar(255),
    rating                 float8,
    primary key (id)
);

create table cloth_reviews
(
    cloth_id int8 not null,
    reviews_id int8 not null
);

create table review
(
    id      int8 generated by default as identity,
    author  varchar(255),
    date    date,
    message varchar(255),
    rating  int4,
    primary key (id)
);

alter table if exists cloth_reviews add constraint UK_gp5u9cs9leiwnbh2rhn27e2w7 unique (reviews_id);
alter table if exists cloth_reviews add constraint FKq51iuslnvq3nw8teocq9y7ag8 foreign key (reviews_id) references review;
alter table if exists cloth_reviews add constraint FK7k3k0ru1omu7xdtdamtrl276 foreign key (cloth_id) references cloth;

create sequence cloth_id_seq start 109 increment 1;