create sequence order_item_seq start 12 increment 1;
create sequence orders_seq start 6 increment 1;

create table orders
(
    id           int8 generated by default as identity,
    address      varchar(255),
    city         varchar(255),
    date         date,
    email        varchar(255),
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar(255),
    credit_card  varchar(255),
    total_price  float8,
    primary key (id)
);

create table order_item
(
    id         int8 generated by default as identity,
    amount     float8,
    quantity   int8,
    cloth_id int8,
    primary key (id)
);

create table orders_order_items
(
    order_id       int8 not null,
    order_items_id int8 not null
);

alter table if exists orders_order_items add constraint UK_9d47gapmi35omtannusv6btu3 unique (order_items_id);
alter table if exists order_item add constraint FKst073lwr6yongjsmgaravadre foreign key (cloth_id) references cloth;
alter table if exists orders_order_items add constraint FK7nw03p9mxq154wvbsonaq0qrw foreign key (order_items_id) references order_item;
alter table if exists orders_order_items add constraint FK3l8rktw0f4w5t6tift31e2d7c foreign key (order_id) references orders;
